extends Node

# Debug para verificar posiciones exactas de colisión

func _ready():
	print("🔍 DEBUG: POSICIONES DE COLISIÓN EXACTAS")
	print("=====================================")
	print("📐 Sala: 1024x576 píxeles")
	print("")
	print("🎯 COLISIONES EN BORDE ABSOLUTO:")
	print("  ⬆️  Superior: x=0-1024, y=0-1 (1px altura)")
	print("  ⬇️  Inferior: x=0-1024, y=575-576 (1px altura)")  
	print("  ⬅️  Izquierda: x=0-1, y=0-576 (1px ancho)")
	print("  ➡️  Derecha: x=1023-1024, y=0-576 (1px ancho)")
	print("")
	print("🎨 VISUALES CENTRADOS:")
	print("  ⬆️  Superior: x=0-1024, y=22-42 (20px altura)")
	print("  ⬇️  Inferior: x=0-1024, y=534-554 (20px altura)")
	print("  ⬅️  Izquierda: x=22-42, y=0-576 (20px ancho)")
	print("  ➡️  Derecha: x=982-1002, y=0-576 (20px ancho)")
	print("")
	print("🧙‍♂️ RESULTADO ESPERADO:")
	print("  - Wizard puede entrar hasta 1px del borde absoluto")
	print("  - Área accesible: 1022x574 píxeles")
	print("  - Penetración en paredes: ~63px en cada lado")
	print("")
	print("🎯 COORDENADAS CRÍTICAS PARA TESTEAR:")
	print("  - Centro superior: (512, 1) - debe chocar")
	print("  - Dentro superior: (512, 30) - debe pasar")
	print("  - Centro izquierda: (1, 288) - debe chocar") 
	print("  - Dentro izquierda: (30, 288) - debe pasar")